import Link from "next/link";

export const metadata={title:"Kuhinja kao centar rutine | DaniniLans",description:"DaniniLans vodič o kuhinji, vodi, receptima, filterima, aparatima i AI beleškama kao centru zdravog stila života bez medicinskih tvrdnji."};

const categories=[
  ["Voda", "Čaša, boca, filter ili bokal čine naviku vidljivom. Voda je osnovni orijentir dana, ne medicinsko obećanje.", "/voda-i-ritam"],
  ["Recepti", "Čaj, sezonski bokal, jednostavan obrok i kuhinjski reset služe ritmu, ne terapiji.", "/recepti"],
  ["Oprema", "Filteri, Welan, UMH kontekst i aparati se obrađuju kao edukativne i praktične teme uz jasne granice tvrdnji.", "/vodici/voda-tehnologija-i-ai"],
  ["AI beleška", "AI pomaže da se napravi lista kupovine, plan pripreme ili pitanje za proveru, ali ne donosi zdravstvene zaključke.", "/vodici/ai-u-svakodnevici"],
];

export default function Page(){return <article className="container section legalText"><div className="eyebrow">Vodič · Kuhinja</div><h1>Kuhinja kao centar rutine i zdravog stila života</h1><p className="lead">Mnoge svakodnevne odluke počinju u kuhinji: voda, čaj, doručak, priprema obroka, filter, aparat, radna površina i beleška za sutra. DaniniLans ne pravi od kuhinje kult, nego je posmatra kao praktično mesto gde se rutina vidi.</p><section className="section featureBand"><div><div className="eyebrow">Kategorije</div><h2>Kuhinja povezuje vodu, recepte, opremu i odluke.</h2></div><p>Ova stranica je čvorište za sadržaj: iz nje se prirodno ide ka vodi, receptima, tehnologiji, AI metodi i disclaimeru. Tako se gradi SEO bez nasumičnog nabacivanja tema.</p></section><section className="grid four">{categories.map(([t,d,href])=><Link className="card" href={href} key={t}><h3>{t}</h3><p>{d}</p><span className="smallCaps">Otvori kategoriju</span></Link>)}</section><section className="card section"><h3>Kako DaniniLans piše o kuhinji</h3><p>Svaki tekst o kuhinji mora imati jasnu ulogu: organizacija dana, voda kao navika, jednostavan recept, priprema prostora ili odgovorna upotreba tehnologije. Ako se pominje zdravlje, tvrdnja se spušta na edukativan i oprezan nivo.</p><div className="ctaRow"><Link className="btn secondary" href="/rutine">Rutine</Link><Link className="btn secondary" href="/stara-znanja">Stara znanja</Link><Link className="btn secondary" href="/disclaimer">Disclaimer</Link></div></section><section className="card disclaimer"><h3>Granica</h3><p>Kuhinja, filteri, aparati, recepti i AI mogu pomoći organizaciji svakodnevice. DaniniLans ih ne predstavlja kao terapiju, dijagnozu ili garanciju zdravstvenog rezultata.</p></section></article>}
